[crawling]
domain = "swiss-badminton.ch"
league_uuid = "4D2A187C-0855-4B4F-B106-6B6413FC17BF"
draws = [14, 62, 63, 64, 67, 68, 69]
datadir = "~/Documents/mada"
data_min_age = 10 # minutes

[crawling.cookies]
"ASP.NET_SessionId" = "h2wt4sdjld4au1luyhhopkm3"
st = "l=2055&exp=45735.9747258333&c=1&cp=51"
lvt = "LHis604hoJcmUJX5L/zG9nozJ7CyOaR29D2YcNgGpWQ="

[display]
club_name = "BC Zürich-Affoltern"

[database]
mongodb = "mongodb://mada-mongo.orb.local:27017"
sqlite_path = "/Users/ricoh/Documents/mada/mada.sqlite"
