"""empty message

Revision ID: 5549be225bd9
Revises: 9e4e42fb2ea4
Create Date: 2025-01-18 23:37:42.859220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5549be225bd9'
down_revision: Union[str, None] = '9e4e42fb2ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doubles_pair',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doubles_pair'))
    )
    op.create_table('player',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player')),
    sa.UniqueConstraint('url', name=op.f('uq_player_url'))
    )
    op.create_table('player_doubles_association',
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['doubles_pair.id'], name=op.f('fk_player_doubles_association_pair_id_doubles_pair')),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_player_doubles_association_player_id_player')),
    sa.PrimaryKeyConstraint('pair_id', 'player_id', name=op.f('pk_player_doubles_association'))
    )
    op.create_table('doubles_result',
    sa.Column('match_date_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('HE1', 'HE2', 'HE3', 'DE1', 'HD1', 'DD1', 'MX1', name='resultcategory'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['match_date_id'], ['matchdate.id'], name=op.f('fk_doubles_result_match_date_id_matchdate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doubles_result'))
    )
    op.create_table('match_result',
    sa.Column('match_date_id', sa.Integer(), nullable=False),
    sa.Column('winner', sa.Enum('HOME', 'AWAY', name='winningteam'), nullable=True),
    sa.Column('walkover', sa.Boolean(), nullable=False),
    sa.Column('home_points', sa.Integer(), nullable=False),
    sa.Column('away_points', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['match_date_id'], ['matchdate.id'], name=op.f('fk_match_result_match_date_id_matchdate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_result'))
    )
    op.create_table('player_teams_association',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_player_teams_association_player_id_player')),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_player_teams_association_team_id_team')),
    sa.PrimaryKeyConstraint('team_id', 'player_id', name=op.f('pk_player_teams_association'))
    )
    op.create_table('singles_result',
    sa.Column('match_date_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('HE1', 'HE2', 'HE3', 'DE1', 'HD1', 'DD1', 'MX1', name='resultcategory'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['match_date_id'], ['matchdate.id'], name=op.f('fk_singles_result_match_date_id_matchdate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_singles_result'))
    )
    op.create_table('away_pair_result',
    sa.Column('doubles_pair_id', sa.Integer(), nullable=False),
    sa.Column('doubles_result_id', sa.Integer(), nullable=False),
    sa.Column('set_1_points', sa.Integer(), nullable=True),
    sa.Column('set_2_points', sa.Integer(), nullable=True),
    sa.Column('set_3_points', sa.Integer(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doubles_pair_id'], ['doubles_pair.id'], name=op.f('fk_away_pair_result_doubles_pair_id_doubles_pair')),
    sa.ForeignKeyConstraint(['doubles_result_id'], ['doubles_result.id'], name=op.f('fk_away_pair_result_doubles_result_id_doubles_result')),
    sa.PrimaryKeyConstraint('doubles_pair_id', 'doubles_result_id', name=op.f('pk_away_pair_result'))
    )
    op.create_table('away_player_result',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('singles_result_id', sa.Integer(), nullable=False),
    sa.Column('set_1_points', sa.Integer(), nullable=True),
    sa.Column('set_2_points', sa.Integer(), nullable=True),
    sa.Column('set_3_points', sa.Integer(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_away_player_result_player_id_player')),
    sa.ForeignKeyConstraint(['singles_result_id'], ['singles_result.id'], name=op.f('fk_away_player_result_singles_result_id_singles_result')),
    sa.PrimaryKeyConstraint('player_id', 'singles_result_id', name=op.f('pk_away_player_result'))
    )
    op.create_table('home_pair_result',
    sa.Column('doubles_pair_id', sa.Integer(), nullable=False),
    sa.Column('doubles_result_id', sa.Integer(), nullable=False),
    sa.Column('set_1_points', sa.Integer(), nullable=True),
    sa.Column('set_2_points', sa.Integer(), nullable=True),
    sa.Column('set_3_points', sa.Integer(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doubles_pair_id'], ['doubles_pair.id'], name=op.f('fk_home_pair_result_doubles_pair_id_doubles_pair')),
    sa.ForeignKeyConstraint(['doubles_result_id'], ['doubles_result.id'], name=op.f('fk_home_pair_result_doubles_result_id_doubles_result')),
    sa.PrimaryKeyConstraint('doubles_pair_id', 'doubles_result_id', name=op.f('pk_home_pair_result'))
    )
    op.create_table('home_player_result',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('singles_result_id', sa.Integer(), nullable=False),
    sa.Column('set_1_points', sa.Integer(), nullable=True),
    sa.Column('set_2_points', sa.Integer(), nullable=True),
    sa.Column('set_3_points', sa.Integer(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_home_player_result_player_id_player')),
    sa.ForeignKeyConstraint(['singles_result_id'], ['singles_result.id'], name=op.f('fk_home_player_result_singles_result_id_singles_result')),
    sa.PrimaryKeyConstraint('player_id', 'singles_result_id', name=op.f('pk_home_player_result'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_player_result')
    op.drop_table('home_pair_result')
    op.drop_table('away_player_result')
    op.drop_table('away_pair_result')
    op.drop_table('singles_result')
    op.drop_table('player_teams_association')
    op.drop_table('match_result')
    op.drop_table('doubles_result')
    op.drop_table('player_doubles_association')
    op.drop_table('player')
    op.drop_table('doubles_pair')
    # ### end Alembic commands ###
